// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace KPoker
{
 public enum CardStrength : byte
{
 Unknown = 0,
 HighCard = 1,
 OnePair = 2,
 TwoPair = 3,
 Triple = 4,
 Straight = 5,
 BackStraight = 6,
 Mountain = 7,
 Flush = 8,
 FullHouse = 9,
 FourCard = 10,
 StraightFlush = 11,
 BackStraightFlush = 12,
 RoyalFlush = 13,
};
 
}
