// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace KPoker
{

public enum Suit : byte
{
 Unknown = 0,
 Club = 1,
 Heart = 2,
 Diamond = 3,
 Spade = 4,
};


}
